### ISSUE TITLE
Invalid ScheduleEvent times

### ISSUE THREAD

**Issue by jleeong** [jleeong/cs48-scheduler#31]
When times are invalid, throws exception and event not made

**Comment by jleeong** [comment]
When a time is negative, the event is made and added to hosted events list with all times excluding the negative timeblock.

When a time > 24, the event is made and includes the invalid timeblock

**Comment by Tianyi6679** [comment]
I am taking on resolving this issue.

**Comment by jleeong** [comment]
resolved by commit 9c3fad4
