### ISSUE TITLE
Create Hosted Event not working for user with no hosted event

### ISSUE THREAD

**Issue by jleeong** [jleeong/cs48-scheduler#33]
The check for existing hosted events prevents a user with an empty hosted events list to add a new hosted event.

Suggested fix: look at the list check in the myHosted list in the DisplayMyHosted tab.

**Comment by jleeong** [comment]
**Ways to recreate error**

1. Login to a user with no Hosted Events or create a new user and login as that new user
2. navigate to My Hosted Events
3. attempt to create any hosted event

**Comment by Tianyi6679** [comment]
Im looking at it .

**Comment by jleeong** [comment]
resolved by commit 9c3fad4
